apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.8.1-jdk-8
    command:
    - sleep
    args:
    - 99d
  - name: golang
    image: golang:latest
    command:
    - sleep
    args:
    - 99d
  - name: maven-alpine
    image: maven:alpine
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
  - name: docker
    image: docker:19.03.1
    readinessProbe:
      exec:
        command: [sh, -c, "ls -S /var/run/docker.sock"]
    command:
    - sleep
    args:
    - 99d
    # volumeMounts:
    # - name: docker-socket
    #   mountPath: /var/run
  # - name: docker-daemon
  #   image: docker:19.03.1-dind
  #   securityContext:
  #     privileged: true
    # volumeMounts:
    # - name: docker-socket
    #   mountPath: /var/run
