apiVersion: v1
kind: Pod
spec:
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  containers:
  - name: maven
    image: maven:3.8.1-jdk-8
    command:
    - sleep
    args:
    - 99d
  - name: golang
    image: golang:latest
    command:
    - sleep
    args:
    - 99d
  - name: maven-alpine
    image: maven:alpine
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
  - name: docker
    image: docker:19.03.1
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
